CREATE TABLE IF NOT EXISTS serial_code (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code CHAR(8) NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS music (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(191) NOT NULL,
    description TEXT NULL,
    itune_url TEXT NULL,
    img_url TEXT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS music_rank (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    serial_code CHAR(8) NOT NULL,
    music_id SMALLINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4;
